server:
  port: 5050
  servlet:
    context-path: /api
    session:
      timeout: PT60M
ws:
  port: 5051
spring:
  mvc:
    favicon:
      enabled: false
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mysql://111.3.116.168:13306/engine_wucheng?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: zjic@cms
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    database: 8
    host: 172.17.114.158
    port: 30079
    password: zjic1951@cmsRedis
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 2000
project:
  folder: c:/easychat
admin:
  emails: test@qq.com
